/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#2563eb",
        "tertiary-fixed": "#d3e4fe",
        "on-tertiary-fixed-variant": "#38485d",
        "on-tertiary-fixed": "#0b1c30",
        "surface-dim": "#d8dadc",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "secondary-container": "#dae2fd",
        "tertiary-container": "#5e6e85",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#131b2e",
        "surface-container": "#eceef0",
        "on-secondary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#dae2fd",
        "on-surface": "#191c1e",
        "background": "#f7f9fb",
        "on-secondary-container": "#5c647a",
        "on-tertiary-container": "#e9f0ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#2d3133",
        "surface-tint": "#0053db",
        "inverse-primary": "#b4c5ff",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#dbe1ff",
        "surface": "#f7f9fb",
        "secondary": "#565e74",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "primary": "#004ac6",
        "tertiary": "#46566c",
        "on-primary-fixed-variant": "#003ea8",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "outline-variant": "#c3c6d7",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#b4c5ff",
        "error": "#ba1a1a",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "on-primary-container": "#eeefff",
        "outline": "#737686",
        "on-secondary-fixed-variant": "#3f465c",
        "on-surface-variant": "#434655"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "clerk": "16px"
      },
      spacing: {
        "unit": "4px",
        "2xl": "48px",
        "gutter": "20px",
        "xs": "4px",
        "container-max": "1440px",
        "lg": "24px",
        "xl": "32px",
        "md": "16px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "sm": "8px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600"}],
        "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        }
      },
      animation: {
        "fade-in-up": "fade-in-up 0.4s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "float": "float 3s ease-in-out infinite",
      }
    },
  },
  plugins: [],
}
