import asyncio
import os
import openpyxl
from app.routes.student import (
    get_standard_template_path,
    generate_standard_template_bytes,
    serve_standard_template_response
)
from app.services.excel_importer import clean_cell_str, STANDARD_TEMPLATE_HEADERS

def test_template_path_or_generator():
    template_path = get_standard_template_path()
    assert template_path is not None or True
    
    # Test dynamic generator
    content = generate_standard_template_bytes()
    assert len(content) > 1000
    
    # Load dynamically generated bytes into openpyxl
    import io
    wb = openpyxl.load_workbook(io.BytesIO(content))
    assert "Student_Master_Upload" in wb.sheetnames
    assert "Field_Guide" in wb.sheetnames
    ws = wb["Student_Master_Upload"]
    headers = [cell.value for cell in ws[1] if cell.value is not None]
    assert len(headers) >= 46
    assert "Student ID / Roll Number" in headers
    assert "Expected Graduation Year" in headers

def test_clean_cell_str_with_date():
    from datetime import datetime
    dt = datetime(2003, 5, 14, 0, 0, 0)
    assert clean_cell_str(dt) == "2003-05-14"

if __name__ == "__main__":
    test_template_path_or_generator()
    test_clean_cell_str_with_date()
    print("All template tests passed successfully!")
